### ISSUE TITLE
Support adding params joined with -

### ISSUE THREAD

**Issue by smlparry** [imgix/imgix-rb#94]
**Is your feature request related to a problem? Please describe.**
I am trying to add `fill-color` to my url and that is not currently supported by the client. I assume other parameters joined with `-` are also not currently supported

**Describe the solution you'd like**
The client should support `fill_color` as such: `client.path(url).fill_color("#fff")`

**Describe alternatives you've considered**
`query.public_send("fill-color", "#ffffff")` does work, but its a bit strange

**Comment by ericdeansanchez** [comment]
Hey @smlparry 👋 thanks for opening this issue. I think supporting this would be cool! In the meantime, you could use:

```rb
client.path(url).fillcolor("#fff")
```

And it would have the same effect.

`fillcolor` would appear in the final URL instead of `fill-color`, but [`fillcolor` is an alias for `fill-color`](https://github.com/imgix/imgix-url-params/blob/864fe17a6c35afa60f6021b6cbcf54c11fed112a/dist/parameters.json#L1054) and the outcome is the same. 

Many imgix parameters have aliases; you can find a complete description of these parameters [here](https://github.com/imgix/imgix-url-params). Each parameter is described in JSON format within the `dist/` directory. If you find anything there you'd like clarification on, please feel free to reach out.

**Comment by smlparry** [comment]
Hey @ericdeansanchez 

Oh i didn't know that! That will fix my issue for now :) Thanks!

**Comment by ericdeansanchez** [comment]
@smlparry Nice! Glad this fixes your issue. I'm working on making these types of things (parameters/aliases) more discoverable, but in the meantime I also worked your specific use-case in right here https://github.com/imgix/imgix-rb/blob/ee2c5e04af7cd7724698764574d18d8341a7b0cf/lib/imgix/path.rb#L86 so using `path("...").fill_color("...")` will work and you'll see it as `fillcolor="..."` in the URL.

For example,

```rb
ixc = Imgix::Client.new(domain: "eric.imgix.net")
ixc.path("brush.JPG").fill_color("28285D").w(500).fill("solid").fill_color("A5AECA").fit("fill").h(600).to_url
```

Which results in

```html
https://eric.imgix.net/brush.JPG?ixlib=rb-4.0.0&fillcolor=A5AECA&w=500&fill=solid&fit=fill&h=600
```
